# Project: lab_11
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = lab_11.o
LINKOBJ  = lab_11.o
LIBS     = -L"D:/Desktop/Dev-Cpp/MinGW64/lib" -L"D:/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Desktop/Dev-Cpp/MinGW64/include" -I"D:/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Desktop/Dev-Cpp/MinGW64/include" -I"D:/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = lab_11.exe
CXXFLAGS = $(CXXINCS) -std=gnu99
CFLAGS   = $(INCS) -std=gnu99 5 10 15 20
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

lab_11.o: lab_11.c
	$(CC) -c lab_11.c -o lab_11.o $(CFLAGS)
